global using UltraDecompiler.CodeGeneration.Rendering;
global using UltraDecompiler.Decompilation;
global using UltraDecompiler.Disassembler;
global using UltraDecompiler.Disassembly.Disassembler;
global using UltraDecompiler.Headers;
global using UltraDecompiler.Ir.Expressions;
global using UltraDecompiler.Ir.Operations;
global using UltraDecompiler.Ir.Procedures;
global using UltraDecompiler.Ir.Variables;
