global using UltraDecompiler.Decompilation;
global using UltraDecompiler.Disassembler;
global using UltraDecompiler.Disassembly.Disassembler;
global using UltraDecompiler.Disassembly.Graph;
global using UltraDecompiler.Disassembly.Parser;
global using UltraDecompiler.Headers;
global using UltraDecompiler.Ir.Builder;
global using UltraDecompiler.Ir.Expressions;
global using UltraDecompiler.Ir.Procedures;
