[dosbox]
memsize=256

[cpu]
cycles=max
turbo=true

[sdl]
output=dummy

[dos]
log console=quiet

[mixer]
nosound = true

[sblaster]
sbtype = none

[gus]
gus = false

[speaker]
pcspeaker = false

[midi]
mpu401 = none
mididevice = none

[autoexec]
MOUNT C ..
C:
SET LIB=C:\QuickC
SET INCLUDE=C:\QuickC\INCLUDE
SET PATH=C:\QuickC;%PATH%
CD \QuickC\PROGRAMS
