# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: 'Install dosbox-x (apt)'
      run: sudo snap install dosbox-x

    - name: Build reference examples
      uses: joncloud/dos-build-action@v1
      with:
        programs: |
          QuickC:C:\QC
        run: |
          C:
          SET LIB=C:\QC
          SET INCLUDE=C:\QC\INCLUDE
          SET PATH=C:\QC;%PATH%
          CD \QC\PROGRAMS
          make clean
          make
        conf: |
          [dosbox]
          memsize=256
          [cpu]
          cycles=max
          turbo=true
          [dos]
          log console=quiet
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
